php:
  preset: laravel
  version: 8
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - show_profile.blade.php.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
